### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by axelson** [MeetMe/jira-gerrit-plugin#1]
Running jira-gerrit-plugin version 1.0 on JIRA v4.3.3 with a query of "message:%s" on Windows server 2003 I get the following stack trace:

2012-12-20 16:09:22,488 http-80-5 ERROR jaxelson 969x11059x1 1hhxeil 172.16.66.245,192.168.0.133 /browse/REG-26 [webwork.util.ValueStack] METHOD: "html", exception: 
java.lang.NullPointerException
  at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:768)
    at com.atlassian.cache.memory.MemoryCache.get(MemoryCache.java:39)
    at com.atlassian.jira.web.bean.I18nBean$CachingFactory.getInstance(I18nBean.java:182)
    at com.atlassian.jira.web.util.OutlookDate.getI18nHelper(OutlookDate.java:534)
    at com.atlassian.jira.web.util.OutlookDate.format(OutlookDate.java:267)
    at com.meetme.plugins.jira.gerrit.tabpanel.GerritReviewIssueAction.formatLastUpdated(GerritReviewIssueAction.java:53)
    at com.meetme.plugins.jira.gerrit.tabpanel.GerritReviewIssueAction.populateVelocityParams(GerritReviewIssueAction.java:46)
    at com.atlassian.jira.plugin.issuetabpanel.AbstractIssueAction.getHtml(AbstractIssueAction.java:21)
    at sun.reflect.GeneratedMethodAccessor903.invoke(Unknown Source)

Full stack trace:
https://gist.github.com/4355393

If I can I will try to look through the code.

**Comment by jhansche** [comment]
@axelson is this still happening with the latest version of the plugin?
