### ISSUE TITLE
Jira Gerrit plugin not working with Jira 7.0.5, 7.0.7 or 7.0.9

### ISSUE THREAD

**Issue by burizz** [MeetMe/jira-gerrit-plugin#30]
The Gerrit Reviews panel in JIRA issues shows no reviews although we can see the reviews in Gerrit. It generates an exception in the JIRA logs (error is below).
It used to work in JIRA 6 before we upgraded to Jira7. I even updated to JIRA 7.0.7 when the update became available but did not help.

2016-01-13 09:25:35,268 http-bio-8443-exec-177 ERROR a.legkiy 565x45073x1 1caebki 194.6.233.46 /rest/greenhopper/1.0/xboard/issue/details.json [c.a.g.w.r.issue.thirdpartytabs.ThirdPartyTabModelFactory] Unable to load third party tab for com.meetme.plugins.jira.gerrit-plugin:gerrit-reviews-agile-panel
java.lang.ClassCastException: com.atlassian.jira.user.BridgedDirectoryUser cannot be cast to com.atlassian.jira.user.ApplicationUser
at com.atlassian.jira.plugin.webfragment.contextproviders.AbstractJiraContextProvider.getContextMap(AbstractJiraContextProvider.java:20)
at com.atlassian.plugin.web.model.AbstractWebItem.getContextMap(AbstractWebItem.java:30)
at com.atlassian.plugin.web.model.DefaultWebLabel.getDisplayableLabel(DefaultWebLabel.java:55)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.buildThirdPartyTab(ThirdPartyTabModelFactory.java:84)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.buildThirdPartyTabs(ThirdPartyTabModelFactory.java:65)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.createModel(ThirdPartyTabModelFactory.java:52)
at com.atlassian.greenhopper.web.rapid.issue.IssueEntryFactory.buildViewEntry(IssueEntryFactory.java:409)
at com.atlassian.greenhopper.web.rapid.issue.IssueResource$1.call(IssueResource.java:136)
at com.atlassian.greenhopper.web.rapid.issue.IssueResource$1.call(IssueResource.java:106)
at com.atlassian.greenhopper.web.util.RestCall.response(RestCall.java:42)
at com.atlassian.greenhopper.web.AbstractResource.createResponse(AbstractResource.java:114)
at com.atlassian.greenhopper.web.AbstractResource.response(AbstractResource.java:94)
at com.atlassian.greenhopper.web.rapid.issue.IssueResource.getPageData(IssueResource.java:105)
... 2 filtered
at java.lang.reflect.Method.invoke(Method.java:497)
... 19 filtered
at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:178)
... 1 filtered
at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:73)
... 101 filtered
at com.atlassian.plugins.rest.module.servlet.RestSeraphFilter.doFilter(RestSeraphFilter.java:40)
... 73 filtered
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by justsomebody42** [comment]
We have the exact same problem...

**Comment by Aricg** [comment]
Bumping

**Comment by wbiller** [comment]
I raised this at Atlassian: https://jira.atlassian.com/browse/JRA-60866

**Comment by jhansche** [comment]
@burizz I believe the 3.0 release of the plugin fixed this, via a pull request from @p00by (#27)

**Comment by jhansche** [comment]
This was fixed in version 3.0, and the latest version 3.1 includes compatibility with 7.0.0 … 7.2.0

**Comment by Prakashjira** [comment]
Hi jhansche,

I have installed JIRA Gerrit Plugin in our Jira Instance Version:3.2. But we are also have same issue. please see the below error.

2017-07-31 04:59:15,658 http-bio-8443-exec-880 ERROR XXXXXXX 299x171879x1 XXXXX XXX.XXX.XXX.XXX /rest/greenhopper/1.0/xboard/issue/details.json [c.a.g.w.r.issue.thirdpartytabs.ThirdPartyTabModelFactory] Unable to load third party tab for com.meetme.plugins.jira.gerrit-plugin:gerrit-reviews-agile-panel

at java.lang.Thread.run(Thread.java:745)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
... 45 filtered
at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:105)
at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:201)
... 31 filtered
at com.atlassian.plugins.rest.module.servlet.RestSeraphFilter.doFilter(RestSeraphFilter.java:37)
... 16 filtered
at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:70)
... 86 filtered
at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:68)
... 1 filtered
at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:154)
... 19 filtered
at java.lang.reflect.Method.invoke(Method.java:498)
... 2 filtered
at com.atlassian.greenhopper.web.rapid.issue.IssueResource.getPageData(IssueResource.java:102)
at com.atlassian.greenhopper.web.AbstractResource.response(AbstractResource.java:91)
at com.atlassian.greenhopper.web.AbstractResource.createResponse(AbstractResource.java:111)
at com.atlassian.greenhopper.web.util.RestCall.response(RestCall.java:42)
at com.atlassian.greenhopper.web.rapid.issue.IssueResource$1.call(IssueResource.java:103)
at com.atlassian.greenhopper.web.rapid.issue.IssueResource$1.call(IssueResource.java:133)
at com.atlassian.greenhopper.web.rapid.issue.IssueEntryFactory.buildViewEntry(IssueEntryFactory.java:401)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.createModel(ThirdPartyTabModelFactory.java:52)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.buildThirdPartyTabs(ThirdPartyTabModelFactory.java:65)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.buildThirdPartyTab(ThirdPartyTabModelFactory.java:84)
at com.atlassian.plugin.web.model.DefaultWebLabel.getDisplayableLabel(DefaultWebLabel.java:55)
at com.atlassian.plugin.web.model.AbstractWebItem.getContextMap(AbstractWebItem.java:30)
at com.atlassian.jira.plugin.webfragment.contextproviders.AbstractJiraContextProvider.getContextMap(AbstractJiraContextProvider.java:20)
java.lang.ClassCastException: com.atlassian.jira.user.BridgedDirectoryUser cannot be cast to com.atlassian.jira.user.ApplicationUser

The solution are expect quickly it will more help to us.

Thanks,
Prakash

**Comment by jhansche** [comment]
Looks like this is specific to the Agile tab panel.  Will reopen this and close #53

**Comment by jhansche** [comment]
The issue is caused by:
```
java.lang.ClassCastException: com.atlassian.jira.user.BridgedDirectoryUser cannot be cast to com.atlassian.jira.user.ApplicationUser
```

That panel comes from https://github.com/MeetMe/jira-gerrit-plugin/blob/master/src/main/resources/atlassian-plugin.xml#L227 so the class would have to be `com.meetme.plugins.jira.gerrit.webpanel.GerritReviewsIssueAgilePanel`

That class was a PR contribution ( #24 ), so I'm not familiar with the code. Perhaps @borgeorgiev has some further insight?

**Comment by Prakashjira** [comment]
Hi jhansche and borgeorgiev,

can we any update on this issue?

**Comment by savaikar** [comment]
Facing similar issues on JIRA 7.2.8 using any of the mentioned Gerrit Plugin versions, 3.0 or 3.3.

**Screenshots:**
![image](https://user-images.githubusercontent.com/13692026/32928605-a1dbadb6-cb78-11e7-96dd-e99b67181e49.png)
![image](https://user-images.githubusercontent.com/13692026/32928608-aa850db8-cb78-11e7-9ca1-af652839698f.png)

Please help!!

**Comment by borgeorgiev** [comment]
Can you provide the errors from the atlassian-jira.log file ?
We're using the addon on JIRA 7.3.1 and Gerrit Plugin 3.2 and it works fine
