### ISSUE TITLE
Need configurable timeout on SSH connection to Gerrit

### ISSUE THREAD

**Issue by ryanrich** [MeetMe/jira-gerrit-plugin#4]
We had our JIRA server run out of threads after installing this plugin -- it looks like there is no timeout set on the ssh connection when it talks to gerrit so this has the possibility of hanging forever.  We had hundreds of threads in the following state in our system:

```
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:129)
at java.net.SocketInputStream.read(SocketInputStream.java:182)
at com.jcraft.jsch.IO.getByte(IO.java:73)
at com.jcraft.jsch.Session.connect(Session.java:230)
at com.jcraft.jsch.Session.connect(Session.java:150)
at com.sonyericsson.hudson.plugins.gerrit.gerritevents.ssh.SshConnectionImpl.<init>(SshConnectionImpl.java:82)
at com.sonyericsson.hudson.plugins.gerrit.gerritevents.ssh.SshConnectionFactory.getConnection(SshConnectionFactory.java:55)
at com.sonyericsson.hudson.plugins.gerrit.gerritevents.GerritQueryHandler.runQuery(GerritQueryHandler.java:226)
at com.sonyericsson.hudson.plugins.gerrit.gerritevents.GerritQueryHandler.queryJava(GerritQueryHandler.java:115)
at com.meetme.plugins.jira.gerrit.data.IssueReviewsImpl.getReviewsFromGerrit(IssueReviewsImpl.java:104)
at com.meetme.plugins.jira.gerrit.data.IssueReviewsImpl.getReviewsForIssue(IssueReviewsImpl.java:76)
at com.meetme.plugins.jira.gerrit.tabpanel.GerritReviewsTabPanel.getActions(GerritReviewsTabPanel.java:114)
at com.meetme.plugins.jira.gerrit.tabpanel.GerritReviewsTabPanel.getActions(GerritReviewsTabPanel.java:82)
at com.atlassian.jira.plugin.issuetabpanel.IssueTabPanelInvokerImpl.invokeGetActions(IssueTabPanelInvokerImpl.java:87)
at com.atlassian.jira.issue.tabpanels.AllTabPanel.getActions(AllTabPanel.java:40)
at com.atlassian.jira.plugin.issuetabpanel.IssueTabPanelInvokerImpl.invokeGetActions(IssueTabPanelInvokerImpl.java:87)
```

**Comment by Jasbris** [comment]
My company also experiences this issue, where at times our Gerrit server under heavy load will be extremely slow to respond and we need to be able to increase our SSH timeout.

(increased timeout relates to performance issues though logged under https://github.com/MeetMe/jira-gerrit-plugin/issues)
