### ISSUE TITLE
JIRA Gerrit Plugin throws error (Unable to load third party tab for com.meetme.plugins.jira.gerrit-plugin:gerrit-reviews-agile-panel)

### ISSUE THREAD

**Issue by Prakashjira** [MeetMe/jira-gerrit-plugin#53]
Hi Team,

We have installed JIRA Gerrit Plugin Version:3.2 in our Jira(7.1.9) Instance. This plugin has throws error (Unable to load third party tab for com.meetme.plugins.jira.gerrit-plugin:gerrit-reviews-agile-panel) 
Please look in to the below error.

```
2017-07-31 04:59:15,658 http-bio-8443-exec-880 ERROR XXXXXXX 299x171879x1 XXXXX XXX.XXX.XXX.XXX /rest/greenhopper/1.0/xboard/issue/details.json [c.a.g.w.r.issue.thirdpartytabs.ThirdPartyTabModelFactory] Unable to load third party tab for com.meetme.plugins.jira.gerrit-plugin:gerrit-reviews-agile-panel

at java.lang.Thread.run(Thread.java:745)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
... 45 filtered
at net.bull.javamelody.JiraMonitoringFilter.doFilter(JiraMonitoringFilter.java:105)
at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:201)
... 31 filtered
at com.atlassian.plugins.rest.module.servlet.RestSeraphFilter.doFilter(RestSeraphFilter.java:37)
... 16 filtered
at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:70)
... 86 filtered
at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:68)
... 1 filtered
at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:154)
... 19 filtered
at java.lang.reflect.Method.invoke(Method.java:498)
... 2 filtered
at com.atlassian.greenhopper.web.rapid.issue.IssueResource.getPageData(IssueResource.java:102)
at com.atlassian.greenhopper.web.AbstractResource.response(AbstractResource.java:91)
at com.atlassian.greenhopper.web.AbstractResource.createResponse(AbstractResource.java:111)
at com.atlassian.greenhopper.web.util.RestCall.response(RestCall.java:42)
at com.atlassian.greenhopper.web.rapid.issue.IssueResource$1.call(IssueResource.java:103)
at com.atlassian.greenhopper.web.rapid.issue.IssueResource$1.call(IssueResource.java:133)
at com.atlassian.greenhopper.web.rapid.issue.IssueEntryFactory.buildViewEntry(IssueEntryFactory.java:401)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.createModel(ThirdPartyTabModelFactory.java:52)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.buildThirdPartyTabs(ThirdPartyTabModelFactory.java:65)
at com.atlassian.greenhopper.web.rapid.issue.thirdpartytabs.ThirdPartyTabModelFactory.buildThirdPartyTab(ThirdPartyTabModelFactory.java:84)
at com.atlassian.plugin.web.model.DefaultWebLabel.getDisplayableLabel(DefaultWebLabel.java:55)
at com.atlassian.plugin.web.model.AbstractWebItem.getContextMap(AbstractWebItem.java:30)
at com.atlassian.jira.plugin.webfragment.contextproviders.AbstractJiraContextProvider.getContextMap(AbstractJiraContextProvider.java:20)
java.lang.ClassCastException: com.atlassian.jira.user.BridgedDirectoryUser cannot be cast to com.atlassian.jira.user.ApplicationUser
```
The solution are expect quickly it will more help to us.

Thanks,
Prakash

**Comment by jhansche** [comment]
The issue is caused by:

```java.lang.ClassCastException: com.atlassian.jira.user.BridgedDirectoryUser cannot be cast to com.atlassian.jira.user.ApplicationUser
```

But your stack trace does not indicate the location where that CCE actually occurs.  But that panel comes from https://github.com/MeetMe/jira-gerrit-plugin/blob/master/src/main/resources/atlassian-plugin.xml#L227 so the class would have to be `com.meetme.plugins.jira.gerrit.webpanel.GerritReviewsIssueAgilePanel`

That class was a PR contribution ( #24 ), so I'm not familiar with the code. Perhaps @borgeorgiev has some further insight?

**Comment by jhansche** [comment]
Will track this in #30.
